% This code reads in the data file generated by calc_3body.m.
% Then it plots the trajectories of three bodies.
%
clear
figure(3);
clf reset
%
load data_3body
%
set(gcf,'position',[100,100,500,500])
axes('position',[0.15,0.12,0.75,0.75])
plot(t,w(:,1),'b-','linewidth',1.0)
hold on
plot(t,w(:,2),'k-','linewidth',1.0)
%
set(gca,'fontsize',14)
axis([-2,42,-1.2,1.2])
set(gca,'xtick',[0:5:40])
set(gca,'ytick',[-2:1:2])
xlabel('t')
ylabel('Body 1, f(t) = (x(t), y(t)')
title('Body 1 as a function of t')
legend('x_1(t), x_1 - coordinate','y_1(t), y_1 - coordinate',2)