% This code reads in the data file generated by calc_3body.m.
% Then it plots the trajectories of three bodies.
%
clear
figure(4);
clf reset
%
load data_3body
T=6.3;
tT=t(:,1)+T;
%
set(gcf,'position',[100,100,500,500])
axes('position',[0.15,0.12,0.75,0.75])
plot(t,w(:,1),'b-','linewidth',3.0)
hold on
plot(t,w(:,2),'k-','linewidth',3.0)
hold on
plot(tT,w(:,1),'r-','linewidth',2.0)
hold on
plot(tT,w(:,2),'g-','linewidth',2.0)
%
set(gca,'fontsize',14)
axis([-2,42,-1.2,1.2])
set(gca,'xtick',[0:5:40])
set(gca,'ytick',[-2:1:2])
xlabel('t')
ylabel('Body 1, f(t) = (x(t), y(t)')
title('Period, T = 6.3, of Body 1')
legend('x_1(t)','y_1(t)','x_1(t+T)','y_1(t+T)',2)