% This code reads in the data file generated by calc_sRK4.m.
% Then it plots the two components of the numerical solution:
% position and velocity.
%
clear
figure(2);
clf reset
%
set(gcf,'position',[100,50,500,600])
set(gcf,'paperposition',[0.5,0.5,7.5,10.0]) 
%
load data_sRK4a
load data_sRK4b
load data_sRK4c
%
ya=wa(1:nstep+1,1)/w0a(1);
yb=wb(1:nstep+1,1)/w0b(1);
yc=wc(1:nstep+1,1)/w0c(1);
axes('position',[0.18,0.56,0.74,0.36])
%
plot(t,ya(1:nstep+1,1),'b-','linewidth',2.0)
hold on
plot(t,yb(1:nstep+1,1),'g-','linewidth', 2.0)
hold on
plot(t,yc(1:nstep+1,1),'r--', 'linewidth', 2.0)
hold on
%
set(gca,'fontsize',14)
axis([-1,26,-1.1,1.1])
set(gca,'xtick',[0:5:25])
set(gca,'ytick',[-1:0.5:1])
xlabel('t_{[0,25]}')
ylabel('W_t=[^{y_t}_{v_t}]  =>  y_t / y_0')
title('Numerical solution by RK4')
h1=legend('y_0=0.1','y_0=1','y_0=1.5');
set(h1,'fontsize',12)
%
axes('position',[0.18,0.09,0.74,0.36])
plot(wa(1:nstep+1,1),wa(1:nstep+1,2),'b-', 'linewidth', 2)
hold on
plot(wb(1:nstep+1,1),wb(1:nstep+1,2),'g-', 'linewidth', 2)
hold on
plot(wc(1:nstep+1,1),wc(1:nstep+1,2),'r--', 'linewidth', 2)
%
set(gca,'fontsize',14)
axis equal
axis([-2.1,2.1,-2.1,2.1])
set(gca,'xtick',[-2:1:2])
set(gca,'ytick',[-2:1:2])
xlabel('Position = y_t')
ylabel('Velocity = v_t')