% This code reads in the data file generated by calc_sRK4.m. Then it
% plots the two components of the numerical solution: position and velocity.
%
clear
figure(4);
clf reset
axes('position',[0.15,0.15,0.75,0.75])
%
load data_sRK4a
load data_sRK4b
%
plot(wa(1:nstep+1,1),wa(1:nstep+1,2),'k-','linewidth',1.0)
hold on
plot(wb(1:nstep+1,1),wb(1:nstep+1,2),'b--','linewidth',1.0)
set(gca,'fontsize',12)
%axis([0,40,-1.1,1.1])
%set(gca,'xtick',[0:10:40])
%set(gca,'ytick',[-1:0.5:1])
xlabel('y(t)')
ylabel('y`(t)')
title('Numerical solution by RK4, W`(t) = [_{y``(t)}^{y`(t)}]')
h1=legend('W(t) = [_{y`(0)=0}^{y(0)=0.25}]','W(t) = [_{y`(0)=4}^{y(0)=-2}]');
set(h1,'fontsize',12)