% This code reads in the data file generated by calc_3body.m.
% Then it plots the trajectories of three bodies.
%
clear
figure(1);
clf reset
%
load data_3body
%
set(gcf,'position',[100,100,500,500])
axes('position',[0.15,0.12,0.75,0.75])
plot(w(:,1),w(:,2),'g-','linewidth',3.0)
hold on
plot(w(:,3),w(:,4),'b-','linewidth',2.0)
hold on
plot(w(:,5),w(:,6),'r-','linewidth',1.0)
%
set(gca,'fontsize',14)
axis equal
axis([-1.2,1.2,-1.2,1.2])
set(gca,'xtick',[-2:1:2])
set(gca,'ytick',[-2:1:2])
xlabel('x')
ylabel('y')
title('Trajectories of three bodies')
legend('Body 1','Body 2','Body 3',2)