% This code reads in the data file generated by calc_3body.m.
% Then it visualizes the trajectories of three bodies.
%
clear
figure(2);
clf reset
%
set(gcf,'position',[100,100,500,500])
set(gcf, 'Backingstore','off')
axes('position',[0.15,0.12,0.75,0.75])
set(gca,'color',[0.2,0.2,0.2])
%
head_1=line('color','g','marker','o','markersize',10,...
    'markerfacecolor','g','erase','background',...
    'xdata',[],'ydata',[]);
head_2=line('color','b','marker','o','markersize',10,...
    'markerfacecolor','b','erase','background',...
    'xdata',[],'ydata',[]);
head_3=line('color','r','marker','o','markersize',10,...
    'markerfacecolor','r','erase','background',...
    'xdata',[],'ydata',[]);
%
body_1=line('color','g','linestyle','-','linewidth',2.5,...
	'erase','background','xdata',[],'ydata',[]);
body_2=line('color','b','linestyle','-','linewidth',2.5,...
	'erase','background','xdata',[],'ydata',[]);
body_3=line('color','r','linestyle','-','linewidth',2.5,...
	'erase','background','xdata',[],'ydata',[]);
%
tail_1=line('color','w','linestyle','-','linewidth',1.0,...
	'erase','none','xdata',[],'ydata',[]);
tail_2=line('color','w','linestyle','-','linewidth',1.0,...
	'erase','none','xdata',[],'ydata',[]);
tail_1=line('color','w','linestyle','-','linewidth',1.0,...
	'erase','none','xdata',[],'ydata',[]);
tail_3=line('color','w','linestyle','-','linewidth',1.0,...
	'erase','none','xdata',[],'ydata',[]);
%
axis equal
axis([-1.2,1.2,-1.2,1.2])
set(gca,'fontsize',14)
set(gca,'xtick',[-2:1:2])
set(gca,'ytick',[-2:1:2])
xlabel('x')
ylabel('y')
title('Trajectories of three bodies')
%
load data_3body
n=size(w,1);
dn=4;
x1=w(1:dn:n,1);
y1=w(1:dn:n,2);
x2=w(1:dn:n,3);
y2=w(1:dn:n,4);
x3=w(1:dn:n,5);
y3=w(1:dn:n,6);
%
nx=size(x1,1);
dib=16/dn;
dit=8/dn;
for i=1:nx,
  set(head_1,'xdata',x1(i),'ydata',y1(i));
  set(head_2,'xdata',x2(i),'ydata',y2(i));
  set(head_3,'xdata',x3(i),'ydata',y3(i));
  ib=max(1,i-dib);
  it=max(1,ib-dit);
  set(body_1,'xdata',x1(ib:i),'ydata',y1(ib:i));
  set(body_2,'xdata',x2(ib:i),'ydata',y2(ib:i));
  set(body_3,'xdata',x3(ib:i),'ydata',y3(ib:i));
  set(tail_1,'xdata',x1(it:ib),'ydata',y1(it:ib));
  set(tail_2,'xdata',x2(it:ib),'ydata',y2(it:ib));
  set(tail_3,'xdata',x3(it:ib),'ydata',y3(it:ib));
  drawnow
  pause(0.01)
end