% This code reads in the data file generated by calc_sRK4.m.
% Then it plots the two components of the numerical solution:
% position and velocity.
%
clear
figure(3);
clf reset
%
set(gcf,'position',[100,50,500,600])
set(gcf,'paperposition',[0.5,0.5,7.5,10.0]) 
%
load data_sRK4c
%
axes('position',[0.18,0.56,0.74,0.36])
%
plot(t,wc(1:nstep+1,1),'r--', 'linewidth', 2.0)
%
set(gca,'fontsize',14)
axis([-1,21,-1.6,1.6])
set(gca,'xtick',[0:5:20])
set(gca,'ytick',[-2:1:2])
xlabel('t_{[0,20]}')
ylabel('y_t')
title('Numerical solution by RK4')
h1=legend('y_0=1.5');
set(h1,'fontsize',12)
%